name: Cypress Tests Chrome
on: [push]
jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cypress run
        uses: cypress-io/github-action@v3
        with:
          project: ./cypress
          browser: chrome
          command: npx cypress run
      
